### ISSUE TITLE
caps+tab没有生效

### ISSUE THREAD

**Issue by LuoPX-15510486969** [Liu233w/CapsLocKeys.ahk#2]
没有生效有两个地方：
1. 图标没有切换
2. 按过caps+tab之后，再输入数字并不是对应的符号，依旧是数字

**Comment by Liu233w** [comment]
大佬，请确定一下你的`CapsLocKeys.ahk`文件的行末符号是不是 CR+LF (windows 行末符)。如果用的是Unix的LF行末的话就会出这个问题
